Add migration script

diff --git a/bin/migrate-prod b/bin/migrate-prod
--- a/bin/migrate-prod
+++ b/bin/migrate-prod
@@ -1,7 +1,13 @@
 #!/bin/bash
 set -e
 
-echo "Are you sure you want to migrate the PRODUCTION db? Has your migration-only pull request been merged? Type MIGRATE if you're sure:"
+if [[ $(git rev-parse --abbrev-ref HEAD) != "master" ]] ; then
+  echo 'Cannot run stg/prod migrations from a branch other than master'
+  exit 1
+fi
+
+echo "Are you sure you want to migrate the PRODUCTION db? Has your migration-only pull request been merged?"
+echo -n "Type MIGRATE if you're sure: "
 read RES
 
 if [ "$RES" != "MIGRATE" ]; then
