Improve build script

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -2,41 +2,45 @@
 
 set -euo pipefail
 
-TYPE=${1:-other}
+main() {
+  release_type=${1:-other}
 
-if [[ $TYPE != "major" ]] &&
-  [[ $TYPE != "minor" ]] &&
-  [[ $TYPE != "patch" ]]
-then
-  echo "Usage: release [major|minor|patch]"
-  exit 1
-fi
+  if [[ $release_type != 'major' ]] &&
+    [[ $release_type != 'minor' ]] &&
+    [[ $release_type != 'patch' ]]
+  then
+    echo 'Usage: release [major|minor|patch]'
+    exit 1
+  fi
 
-if [[ $(git rev-parse --abbrev-ref HEAD) != "master" ]] ; then
-  echo 'Cannot release from a branch other than master'
-  exit 1
-fi
+  if [[ $(git rev-parse --abbrev-ref HEAD) != 'master' ]] ; then
+    echo 'Cannot release from a branch other than master'
+    exit 1
+  fi
 
-if [[ $(git describe --exact-match --tags HEAD 2> /dev/null) ]] ; then
-  echo 'Current commit is already a tag commit; not releasing it again'
-  exit 1
-fi
+  if [[ $(git describe --exact-match --tags HEAD 2> /dev/null) ]] ; then
+    echo 'Current commit is already a tag commit; not releasing it again'
+    exit 1
+  fi
 
-if [[ $(git status --porcelain) != "" ]] ; then
-  echo 'Cannot release with uncommitted changes'
-  exit 1
-fi
+  if [[ $(git status --porcelain) != '' ]] ; then
+    echo 'Cannot release with uncommitted changes'
+    exit 1
+  fi
 
-git fetch origin
-git pull --rebase origin master
+  git fetch origin
+  git pull --rebase origin master
 
-npm version $TYPE
+  npm version $release_type
 
-git push origin master --follow-tags
+  git push origin master --follow-tags
 
-git checkout -B production
-git pull --rebase origin production
-git rebase master
-git push origin production
+  git checkout -B production
+  git pull --rebase origin production
+  git rebase master
+  git push origin production
 
-git checkout master
+  git checkout master
+}
+
+main "$@"
