update validate-migration script

diff --git a/validate-migration b/validate-migration
--- a/validate-migration
+++ b/validate-migration
@@ -7,10 +7,10 @@ c_red=$'\033[0;31m'
 c_yellow=$'\033[1;33m'
 c_reset=$'\033[0m'
 
-data_backup_path=$TMPDIR/cala-db-data-backup.txt
-before_migration_path=$TMPDIR/cala-db-before-migration.txt
-after_migration_path=$TMPDIR/cala-db-after-migration.txt
-after_rollback_path=$TMPDIR/cala-db-after-rollback.txt
+initial_data_path=$TMPDIR/cala-db-initial-schema.txt
+initial_schema_path=$TMPDIR/cala-db-before-migration.txt
+after_migration_schema_path=$TMPDIR/cala-db-after-migration.txt
+after_rollback_schema_path=$TMPDIR/cala-db-after-rollback.txt
 
 db_url='postgres://localhost/cala-test'
 
@@ -33,23 +33,28 @@ post() {
 }
 
 restore_data() {
-  psql $db_url < $data_backup_path > /dev/null
+  pre 'Restoring initial schema... '
+  psql $db_url < $initial_schema_path > /dev/null
+  post
+
+  pre 'Restoring initial data... '
+  psql $db_url < $initial_data_path > /dev/null
+  post
 }
 
 fail_elegantly() {
-  echo -n $c_red"Unable to complete migration. Restoring initial data..."$c_reset
+  echo $c_red"Unable to complete migration."$c_reset
   restore_data
-  post
   exit 1
 }
 
 main() {
   pre 'Dumping initial data... '
-  pg_dump -c $db_url > $data_backup_path
+  pg_dump -c $db_url > $initial_data_path
   post
 
   pre 'Dumping initial schema... '
-  pg_dump -sOx $db_url > $before_migration_path
+  pg_dump -csOx $db_url > $initial_schema_path
   post
 
   pre 'Migrating... '
@@ -57,7 +62,7 @@ main() {
   post
 
   pre 'Dumping migrated schema... '
-  pg_dump -sOx $db_url > $after_migration_path
+  pg_dump -csOx $db_url > $after_migration_schema_path
   post
 
   pre 'Rolling back... '
@@ -65,18 +70,16 @@ main() {
   post
 
   pre 'Dumping final schema... '
-  pg_dump -sOx $db_url > $after_rollback_path
+  pg_dump -csOx $db_url > $after_rollback_schema_path
   post
 
-  pre 'Restoring initial data... '
   restore_data
-  post
 
   echo $c_yellow'Schema difference after migration (should be non-zero):'$c_reset
-  diff $before_migration_path $after_migration_path || true
+  diff $initial_schema_path $after_migration_schema_path || true
 
   echo $c_yellow'Schema difference after applying and rolling back (should be zero):'$c_reset
-  diff $before_migration_path $after_rollback_path
+  diff $initial_schema_path $after_rollback_schema_path
 }
 
 main "$@"
